# Generated by Django 5.0.14 on 2026-01-08 00:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['fecha_mensaje']},
        ),
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(default='texto', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_chat_pair'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(check=models.Q(('user1', models.F('user2')), _negated=True), name='no_self_chat'),
        ),
    ]
