# Generated by Django 5.0.14 on 2026-01-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_mensaje_options_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
