# Generated by Django 5.1.4 on 2026-06-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mensaje_imagen_alter_mensaje_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='es_recibido',
            field=models.BooleanField(default=False),
        ),
    ]
