# Generated by Django 5.1.4 on 2026-06-19 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_mensaje_es_recibido'),
        ('stories', '0003_story_audio_story_audio_inicio_story_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='stories.story'),
        ),
    ]
