# Generated by Django 5.1.4 on 2026-06-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_mensaje_story'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS llamada_log (
                id BIGSERIAL PRIMARY KEY,
                chat_id BIGINT NOT NULL,
                llamante_id BIGINT NOT NULL,
                receptor_id BIGINT NOT NULL,
                inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                fin TIMESTAMP WITHOUT TIME ZONE NULL,
                duracion_segundos INTEGER NULL,
                estado VARCHAR(20) NOT NULL DEFAULT 'iniciada'
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS llamada_log;",
        ),
    ]
