# Generated by Django 5.1.4 on 2026-06-20 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_llamadalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('respondida', 'Respondida'), ('rechazada', 'Rechazada'), ('perdida', 'Perdida'), ('finalizada', 'Finalizada')], default='iniciada', max_length=20)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='chat.chat')),
                ('llamante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llamada_log',
                'ordering': ['-inicio'],
            },
        ),
    ]
