# Generated by Django 5.0.14 on 2025-12-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='enviada',
            field=models.BooleanField(default=False),
        ),
    ]
