# Generated by Django 5.0.14 on 2026-01-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificacion_enviada'),
        ('publications', '0011_alter_comentario_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='enviada',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='publications.post'),
        ),
    ]
