# Generated by Django 5.0.14 on 2026-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificacion_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
