"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1').split(',') + ['milanesa.shop', 'www.milanesa.shop', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'daphne', # <--- Necesario para que runserver use ASGI/WebSockets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'users',
    'home',
    'traffic',
    'profiles',
    'notifications',
    'chat',
    'publications',
    'webpush',
    'recommendations',
    'ai_assistant',
]
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv('VAPID_PUBLIC_KEY'),
    "VAPID_PRIVATE_KEY": os.getenv('VAPID_PRIVATE_KEY'),
    "VAPID_ADMIN_EMAIL": os.getenv('VAPID_ADMIN_EMAIL'),
    'AUTOMATIC_SUBSCRIPTION': False 
}




MIDDLEWARE = [
    'traffic.middleware.TrafficMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media', 
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Guayaquil'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://milanesa.shop',
    'https://www.milanesa.shop',

    # Si usas más dominios o subdominios, añádelos aquí también
]


LOGIN_REDIRECT_URL = 'index' 

LOGIN_URL = '/users/login/'


AUTH_USER_MODEL = 'users.Usuarios'


#LOGGING = {
    #'version': 1,
    #'disable_existing_loggers': False,
    #'handlers': {
    #    'file': {
    #        'level': 'INFO',
    #        'class': 'logging.FileHandler',
    #        'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
    #    },
    #},
    #'loggers': {
    #    'django': {
    #        'handlers': ['file'],
    #        'level': 'INFO',
   #         'propagate': True,
  #      },
 #}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CLOUDFLARE CONFIGURATION
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
SECURE_HSTS_SECONDS = 31536000 if os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True' else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CRÍTICO PARA CLOUDFLARE/NGINX:
# Dice a Django: "Si el header X-Forwarded-Proto es https, confía en que es seguro aunque yo reciba http"
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cloudflare trusted IPs
SECURE_PROXY_TRUSTED_IPS = '*'

# WebSocket configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv('CHANNELS_REDIS_HOST', '127.0.0.1'), int(os.getenv('CHANNELS_REDIS_PORT', 6379)))],
            "capacity": 3000,  # Aumentado para soportar más conexiones simultáneas
            "expiry": 60,  # Aumentado para no expirar conexiones activas
            # Keepalive para WebSockets
            "group_expiry": 900,
        },
    },
}

# DAPHNE/ASGI Configuration
ASGI_APPLICATION = 'web.asgi.application'

# WebSocket timeout settings para evitar desconexiones
WEBSOCKET_ACCEPT_ALL = False  # Validar conexiones
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB para uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
