# Generated by Django 5.0.14 on 2026-01-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0011_alter_comentario_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ManyToManyField(related_name='trending_analyses', to='publications.post')),
            ],
            options={
                'verbose_name': 'Análisis de Tendencias',
                'verbose_name_plural': 'Análisis de Tendencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
