# Generated by Django 5.1.4 on 2026-06-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='stories/audio/'),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_inicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='duracion',
            field=models.IntegerField(default=30),
        ),
    ]
