# Generated by Django 5.0.12 on 2025-02-26 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seguidores'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguidores',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seguidores',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='siguiendo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seguidores',
            name='seguido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='seguidores',
            name='id_user',
        ),
    ]
