# Generated by Django 5.0.12 on 2025-02-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_seguidores_unique_together_seguidores_usuario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguidores',
            unique_together={('usuario', 'seguido')},
        ),
    ]
