# Generated by Django 5.0.12 on 2025-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_seguidores_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
