# Generated by Django 5.0.12 on 2025-02-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuarios_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
