# Generated by Django 5.0.14 on 2025-12-12 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usuarios_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('endpoint', models.CharField(max_length=255, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispositivo_sesion',
            },
        ),
    ]
