# Generated by Django 5.0.14 on 2025-12-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_dispositivosesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivosesion',
            name='endpoint',
            field=models.TextField(),
        ),
    ]
