# Generated by Django 5.0.14 on 2026-01-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_dispositivosesion_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verification_badges',
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='musica_inicio',
            field=models.FileField(blank=True, null=True, upload_to='musica_inicio/'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='verification_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.verificationbadge'),
        ),
    ]
