# Generated by Django 5.0.14 on 2026-01-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_verificationbadge_usuarios_musica_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
