# Generated by Django 5.0.14 on 2026-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usuarios_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_messages_check',
            field=models.DateTimeField(blank=True, help_text='Para gestionar el badge global de mensajes', null=True),
        ),
    ]
