# Generated by Django 5.1.4 on 2026-06-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usuarios_last_messages_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
