# Generated by Django 5.0.12 on 2025-03-21 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('reacciones', models.IntegerField(choices=[(1, 'Me encanta'), (2, 'Me divierte'), (3, 'Me entristece'), (4, 'Me enoja')], default=1)),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], max_length=50)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='profiles.perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('reacciones', models.IntegerField(choices=[(1, 'Me encanta'), (2, 'Me divierte'), (3, 'Me entristece'), (4, 'Me enoja')], default=1)),
                ('estado', models.BooleanField(default=True)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='publications.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publications.post')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
