# Generated by Django 5.0.12 on 2025-03-21 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuarios_etiquetados',
            field=models.ManyToManyField(blank=True, related_name='etiquetados_en_comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='usuarios_etiquetados',
            field=models.ManyToManyField(blank=True, related_name='etiquetados_en_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
