# Generated by Django 5.0.12 on 2025-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
