# Generated by Django 5.0.12 on 2025-03-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
