# Generated by Django 5.0.14 on 2025-12-09 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_alter_post_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo_musica', models.FileField(upload_to='musica/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
                'db_table': 'musica',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_asociados', to='publications.musica'),
        ),
    ]
