# Generated by Django 5.0.14 on 2025-12-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_musica_post_musica'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='musica_fin',
            field=models.IntegerField(default=15, help_text='Segundo de fin'),
        ),
        migrations.AddField(
            model_name='post',
            name='musica_inicio',
            field=models.IntegerField(default=0, help_text='Segundo de inicio'),
        ),
    ]
