# Generated by Django 5.0.14 on 2026-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_post_musica_fin_post_musica_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios_imagenes/'),
        ),
    ]
