# Generated by Django 5.0.14 on 2026-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_comentario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
