# Generated by Django 5.1.4 on 2026-02-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_alter_comentario_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='posts/imagenes/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='publications.post')),
            ],
            options={
                'db_table': 'post_imagen',
                'ordering': ['orden'],
            },
        ),
    ]
