# Generated by Django 5.1.4 on 2026-02-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_migrate_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
