# Generated by Django 5.1.4 on 2026-02-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_remove_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimagen',
            name='imagen',
            field=models.FileField(upload_to='posts/imagenes/'),
        ),
    ]
