# Generated by Django 5.1.4 on 2026-02-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_alter_postimagen_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usuarios_etiquetados',
        ),
    ]
