# Generated by Django 5.1.4 on 2026-02-13 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_remove_post_usuarios_etiquetados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usuarios_etiquetados',
            field=models.ManyToManyField(blank=True, related_name='etiquetados_en_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
