# Generated by Django 5.1.4 on 2026-06-25 05:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(help_text='e.g., 1.1, 2.1', max_length=20)),
                ('document_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('ai_critique', 'AI Critique Terms'), ('full_package', 'Full Legal Package')], max_length=20)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=2)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_hash', models.CharField(help_text='SHA-256 of the document text', max_length=64)),
            ],
            options={
                'verbose_name': 'Terms Version',
                'verbose_name_plural': 'Terms Versions',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserConsent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(blank=True, editable=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('desktop', 'Desktop')], default='web', max_length=20)),
                ('consent_method', models.CharField(choices=[('registration', 'Registration'), ('update_prompt', 'Update Prompt')], default='update_prompt', max_length=20)),
                ('ai_critique_accepted', models.BooleanField(default=False)),
                ('ai_critique_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('terms_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='legal.termsversion')),
            ],
            options={
                'verbose_name': 'historical User Consent',
                'verbose_name_plural': 'historical User Consents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('desktop', 'Desktop')], default='web', max_length=20)),
                ('consent_method', models.CharField(choices=[('registration', 'Registration'), ('update_prompt', 'Update Prompt')], default='update_prompt', max_length=20)),
                ('ai_critique_accepted', models.BooleanField(default=False)),
                ('ai_critique_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consents', to='legal.termsversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
            },
        ),
    ]
